export enum ActionType {
  AUTHENTICATING = "AUTHENTICATING",
  AUTHENTICATED = "AUTHENTICATED",
  POSTS = "POSTS",
  CLEAR_POSTS = "CLEAR_POSTS",
  INSERT_POST = "INSERT_POST",
  UPDATE_POST = "UPDATE_POST",
}
