export enum ModelType {
  USER = 'users',
  POST = 'posts',
  IMAGE = 'images',
}

export enum ResponseCode {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  SERVER_ERROR = 'SERVER_ERROR',
  INPUT_ERROR = 'INPUT_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  DATABASE_ERROR = 'DATABASE_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INVALID_MIMETYPE = 'INVALID_MIMETYPE',
  MAX_FILE_SIZE = 'MAX_FILE_SIZE',
  FILE_MISSING = 'FILE_MISSING',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
}

export enum RedisDB {
  SESSION = 0,
  CACHE = 1,
}
