name: Run Tests
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      #  External docker build cache sources and destinations
      CACHE_FROM: type=local,src=/tmp/.buildx-cache
      CACHE_TO: type=local,dest=/tmp/.buildx-cache-new,mode=max

    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy & Create Environment Variables
        run: |
          cp ./backend/.env.example ./backend/.env

      - name: Run Backend Tests
        id: backend-test
        shell: bash
        run: |
          docker-compose \
          --env-file ./backend/.env \
          -p cms-blog-test-stack \
          -f ./backend/docker-compose.yml \
          -f ./backend/docker-compose.test.yml \
          up --build \
          --abort-on-container-exit api-server

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

        # Temp fix to prevent GitHub's limit of 5GB.
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move & Clear Cache
        run: |
          # Check if the source directory exists
          if [ -d /tmp/.buildx-cache-new ]; then
            # Remove the existing destination directory
            rm -rf /tmp/.buildx-cache
            
            # Move the source directory to the destination
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          fi
